theme: jekyll-theme-slate
title: Tulsa Musician Legal Pay Activism 
description: The goal of this page is to help musicians know their rights under the FMLA and directly advocate for those rights with institutions that are violating the law.
