theme: jekyll-theme-slate
title: Tulsa Musician Legal Pay Activism 
description: The goal is to help musicians and organizations know their rights under the FMLA and directly advocate for those rights when employers are breaking the law.
